### ISSUE TITLE
Release v1.1.0.0 detected as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by ZenomeFR** [UHAXM1/Quantum#2]
Hi,
Thanks for this awesome tool :) 
I tried to update to the [v1.1.0.0] this morning but unfortunatly Windows Defender flagged the [Quantum_Setup.exe] as Trojan:Win32/Wacatac.B!ml

EDIT: Chrome is also detecting the Portable version as a virus.

Thanks for your support
Zenome

**Comment by UHAXM1** [comment]
I am sure this is a false positive, I ran each package through VirusTotal the setup got a hit on Bkav Pro for W32.AIDetectMalware. The portable zip version reported a positive on MaxSecure for Trojan.Malware.300983.susgen.

I think these are being reported because Quantum uses a library that has been used by other programs and has been flagged as malicious. If I unpack the portable version and run each file through VirtusTotal one at a time, I get no reported virus.

I also tried scanning with Windows Defender, but it came back clean. Can you please confirm the md5 checksums for both files? mine are.

Quantum_Setup.exe
d9436433474e663f0553e1ba4f385201

Quantum_Portable.zip
8cf2eeeebfb4b3f43370e72155027232

**Comment by ZenomeFR** [comment]
Hi,

Same checksums, downloaded from github :)
I've tried it with VirusTotal too and no issues detected... I don't really know why it's detected

**Comment by UHAXM1** [comment]
Good to know, I will keep this issue open for a few days while I do more investigating.

Thanks for your help!
